import Head from 'next/head'
import styles from '../styles/Home.module.css'
import getInitialServerSideState from "../apollo/getInitialSSRState";
import { useQuery } from "@apollo/client";
import { GET_ROCKETS } from "../apollo/query";

function Page() {
  const { data, loading } = useQuery(GET_ROCKETS, {
    fetchPolicy: "cache-first",
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        {loading && <div>Loading</div>}
        {!loading && data?.launchesPast.map((launch) => (
          <div key={launch.id}>
            <span>
              {launch.rocket.rocket_name}&nbsp;
            </span>
          </div>
        ))}

      </main>
    </div>
  )
}

export async function getServerSideProps(ctx) {
  const initialSSRState = await getInitialServerSideState(ctx);

  return {
    props: {
      ...initialSSRState,
    },
  };
};

export default Page;
